### ISSUE TITLE
Download Page Returns 404 Error on Project Website

### ISSUE THREAD

**Issue by Shawyeok** [eclipse-mat/website#2]
The download button on the legacy Eclipse MAT project website (https://projects.eclipse.org/projects/tools.mat/downloads) returns a 404 error page when clicked. This affects new users attempting to download the Memory Analyzer Tool.

<img width="1153" alt="Image" src="https://github.com/user-attachments/assets/bddfd99b-f777-46fc-a73b-a29b16d503fe" />

<img width="1072" alt="Image" src="https://github.com/user-attachments/assets/834e9f3b-204c-4de8-b94c-af6550cf3cb0" />

The issue can be worked around by using the new official Eclipse MAT website at https://eclipse.dev/mat/, where the download functionality works correctly.

Steps to reproduce:
1. Visit https://projects.eclipse.org/projects/tools.mat/downloads
2. Click on download button
3. Observe that the page returns a 404 error

Impact:
- Users following older documentation or links may be unable to download the tool
- Creates confusion for new users trying to set up Eclipse MAT

Suggested actions:
1. Either redirect the old download page to the new website
2. Or update the legacy page to point users to the new Eclipse MAT website at https://eclipse.dev/mat/

**Comment by fedejeanne** [comment]
I tried the [official site](https://eclipse.dev/mat/download/) and clicked on the orange [download button](https://eclipse.dev/mat/download/download) on the top right corner but it doesn't work either. This might be a consequence of the general [outage that happened between April and May](https://www.eclipsestatus.io/incident/549796).

In any case, I was able to update my current installation by clicking _Help > Search for Updates_. It picked up version **1.15** (not the latest stable). Version 1.15 is also available under [previous releases](https://eclipse.dev/mat/download/previous/)

**Comment by kgibm** [comment]
Fixed on both:

* <https://projects.eclipse.org/projects/tools.mat/downloads>
* <https://eclipse.dev/mat/>

**Comment by fedejeanne** [comment]
The orange download button in https://eclipse.dev/mat/download/ still doesn't work for me: I get a 404.

It's this URL: https://eclipse.dev/mat/download/download

**Comment by kgibm** [comment]
Opened https://github.com/eclipse-mat/website/pull/3

**Comment by krumts** [comment]
Thanks, Kevin, and sorry for the delay!
